### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by yeus** [rohitrango/Image-Quilting-for-Texture-Synthesis#1]
Hi, I really like your work. Could you add a license to the code? Otherwise it is not possible to use it in other projects --> The license of similar works is MIT if that helps, but of course its entirely your choice.

https://github.com/PJunhyuk/ImageQuilting/blob/master/LICENSE

So it might make sense to just use the same license. Thx!

Best, 
Thomas

**Comment by rohitrango** [comment]
Hi Thomas,

I've added a LICENSE.
